server:
  port: 8080


spring:
  application:
    name: User-SERVICE
  data:
    mongodb:
      host: localhost
      database: Users
  main:
    allow-bean-definition-overriding: true
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost