server:
  port: 9191

spring:
  application:
    name: API-GATEWAY



  cloud:
    gateway:
      routes:
        - id: User-SERVICE
          uri: lb://User-SERVICE
          predicates:
            - Path=/user/**
        - id: DealsAndCoupons-SERVICE
          uri: lb://DealsAndCoupons-SERVICE
          predicates:
            - Path=/deals/**






#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost